[project]
name = "advent"
version = "2025"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
day01 = "advent.day01.day01:day01"
day02 = "advent.day02.day02:day02"

[tool.setuptools]
packages = ["advent"]
